#!/bin/bash

#
# svg_rect
# Sparisoma Viridi | https://github.com/dudung/bash-svg
#
# 20221006 Start this script.
#

# check number of arguments
if [ $# -lt 4 ]
then
  echo "Usage: svg_rec x=num y=num w=num h=num"
  echo "x      coordinate from left margin"
  echo "y      coordinate from top margin"
  echo "w      width of rectange"
  echo "h      height of rectangle"
  echo "num    any positif numerical values"
  exit
fi

x=$(echo $@ | cut -d'x' -f2)
echo $x
#x="dsf"

if [ -z $x ]
then
  echo $x exists
fi

echo $x