#!/bin/bash

#
# svg_beg
# Sparisoma Viridi | https://github.com/dudung
#
# 20220920 Create this script.
#

# define parameters
xml_declaration="<?xml version='1.0'?>"
xmlns="http://www.w3.org/2000/svg"
xmlns_link="http://www.w3.org/1999/xlink"
xmin=0
ymin=0
xmax=100
ymax=100
width=200
height=200

# print svg opening tag
echo $xml_declaration
echo "<svg"
echo " xmlns=\"$xmlns\""
echo " xmlns:link=\"$xmlns_link\""
echo " viewBox=\"$xmin $ymin $xmax $ymax\""
echo ">"